default:
  image: docker:20.10.16-dind
  tags:
    - intern
    - docker

stages:
  - build
  - deploy
  - clear

variables:
  IMAGE_BASE: "$CI_REGISTRY/$CI_PROJECT_PATH"
  IMAGE_COMMIT: "$IMAGE_BASE:$CI_COMMIT_SHORT_SHA"

before_script:
  - export VERSION_NR=$(cat ./VERSION)
  - export VERSION_COMMIT="${VERSION_NR}-${CI_COMMIT_SHORT_SHA}"
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

# Template
.cleanup_job: &cleanup_job
  script:
    - docker rmi -f $(docker images | grep $IMAGE_BASE | awk '{print $3}') || true
  only:
    - master

clear_first:
  stage: build
  <<: *cleanup_job

build:
  stage: build
  script:
    - docker build . --pull -t $IMAGE_COMMIT
  only:
    - master
  needs:
    - job: clear_first

deploy:
  stage: deploy
  script:
    - IMAGE_ID=$(docker images | grep "$CI_COMMIT_SHORT_SHA" | awk '{print $3}')
    # Tag
    - docker tag $IMAGE_ID "$IMAGE_BASE:$VERSION_NR"
    - docker tag $IMAGE_ID "$IMAGE_BASE:$VERSION_COMMIT"
    - docker tag $IMAGE_ID "$IMAGE_BASE:latest"
    # Push
    - docker push "$IMAGE_BASE:$VERSION_COMMIT"
    - docker push "$IMAGE_BASE:$VERSION_NR"
    - docker push $IMAGE_BASE:latest
  only:
    - master

#
# Clean
#

clear_success:
  stage: clear
  when: on_success
  <<: *cleanup_job

clear_failure:
  stage: clear
  when: on_failure
  <<: *cleanup_job
