version: "3"

services:

  srv:
    restart: "always"
    image: zarix/kivitendo_docker
    ports:
      - 8080:80
    volumes:
      - ./template1:/var/www/kivitendo-erp/templates/template1
    depends_on:
      - db

  db:
    restart: "always"
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: kivitendo
      POSTGRES_USER: kivitendo
      POSTGRES_DB: kivitendo_auth
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
